# Generated by Django 4.0.4 on 2022-04-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_category_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='catogory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.category'),
        ),
    ]
